const categories=["Bruit","Accident","Incendie","Agression","Point de deal","Circulation","Déchets","Dégradation","Odeurs","Salubrité","Autre"];
const periods=[["today","Aujourd’hui"],["7d","7 derniers jours"],["30d","30 derniers jours"],["6m","6 derniers mois"],["ytd","Depuis le début de l’année"],["launch","Depuis le lancement"]];
const communes=["Saumur","Allonnes","Antoigné","Artannes-sur-Thouet","Bellevigne-les-Châteaux","Blou","Brain-sur-Allonnes","La Breille-les-Pins","Brossay","Cizay-la-Madeleine","Le Coudray-Macouard","Courchamps","Courléon","Dénezé-sous-Doué","Distré","Doué-en-Anjou","Épieds","Fontevraud-l'Abbaye","Gennes-Val-de-Loire","La Lande-Chasles","Longué-Jumelles","Louresse-Rochemenier","Montreuil-Bellay","Montsoreau","Mouliherne","Neuillé","Parnay","Le Puy-Notre-Dame","Rou-Marson","Saint-Clément-des-Levées","Saint-Just-sur-Dive","Saint-Macaire-du-Bois","Saint-Philbert-du-Peuple","Souzay-Champigny","Tuffalun","Turquant","Les Ulmes","Varennes-sur-Loire","Varrains","Vaudelnay","Vernantes","Vernoil-le-Fourrier","Verrie","Villebernier","Vivy"];
const colors={Bruit:"#6f42c1",Accident:"#dc3545",Incendie:"#e8590c",Agression:"#b02a37","Point de deal":"#343a40",Circulation:"#1971c2",Déchets:"#2b8a3e",Dégradation:"#7950f2",Odeurs:"#087f5b",Salubrité:"#495057",Autre:"#868e96"};
const populationSaumur=26241,populationAgglo=98005,saumur=[47.259,-0.0769];
let period="30d",reports=[],reportsSaumur=[],reportsAgglo=[],map,pickMap,markers=L.layerGroup(),pickMarker;
const $=id=>document.getElementById(id);
document.querySelector("#periods").innerHTML=periods.map(([v,l])=>`<button data-p="${v}" class="${v===period?"active":""}">${l}</button>`).join("");
document.querySelector("#catfilter").innerHTML='<option>Toutes</option>'+categories.map(x=>`<option>${x}</option>`).join("");
document.querySelector("#communeFilter").innerHTML='<option value="Toutes">Toutes les communes</option>'+[...new Set(communes)].map(x=>`<option>${x}</option>`).join("");
document.querySelector("#territory").innerHTML='<option value="">Commune</option>'+[...new Set(communes)].map(x=>`<option>${x}</option>`).join("");
document.querySelectorAll("#periods button").forEach(b=>b.onclick=()=>{period=b.dataset.p;document.querySelectorAll("#periods button").forEach(x=>x.classList.toggle("active",x===b));load()});
$("scope").onchange=async()=>{const agg=$("scope").value==="Agglo";$("communeFilter").style.display=agg?"block":"none";await recenterSelection();await load()};
$("communeFilter").onchange=async()=>{await recenterSelection();await load()};$("catfilter").onchange=load;
$("category").onchange=()=>{$("other").hidden=$("category").value!=="Autre";$('other').required=$("category").value==="Autre"};
map=L.map("map").setView(saumur,11);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{attribution:"© OpenStreetMap contributors"}).addTo(map);markers.addTo(map);
pickMap=L.map("pickmap").setView(saumur,14);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{attribution:"© OpenStreetMap contributors"}).addTo(pickMap);pickMap.on("click",e=>setPick(e.latlng.lat,e.latlng.lng));
function setPick(lat,lon){if(pickMarker)pickMap.removeLayer(pickMarker);pickMarker=L.marker([lat,lon]).addTo(pickMap);$("address").dataset.lat=lat;$("address").dataset.lon=lon}
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
async function fetchReports(territory){const p=new URLSearchParams({period});const cat=$("catfilter").value;if(cat&&cat!=="Toutes")p.set("category",cat);if(territory)p.set("territory",territory);const r=await fetch("/api/reports?"+p);return r.ok?r.json():[]}
async function load(){try{[reportsSaumur,reportsAgglo]=await Promise.all([fetchReports("Saumur"),fetchReports(null)]);const agg=$("scope").value==="Agglo";if(agg){const c=$("communeFilter").value;reports=c!=="Toutes"?reportsAgglo.filter(x=>x.territory===c):reportsAgglo}else reports=reportsSaumur}catch(e){reports=[];reportsSaumur=[];reportsAgglo=[]}render()}
function render(){markers.clearLayers();reports.forEach(x=>{const m=L.circleMarker([x.lat,x.lon],{radius:7,color:colors[x.category]||"#555",fillColor:colors[x.category]||"#555",fillOpacity:.85});m.bindPopup("<b>"+esc(x.category)+"</b>"+(x.subtype?" — "+esc(x.subtype):"")+"<br><b>Commune :</b> "+esc(x.territory)+"<br><b>Adresse :</b> "+esc(x.address)+"<br>"+new Date(x.created_at).toLocaleString("fr-FR")+(x.description?"<br><br>"+esc(x.description):""));markers.addLayer(m)});$("total").textContent=reports.length;$("heroTotal").textContent=reports.length;const cityRate=reportsSaumur.length/populationSaumur*100000;const aggRate=reportsAgglo.length/populationAgglo*100000;$("rateSaumur").textContent=cityRate.toFixed(1);$("rateAgglo").textContent=aggRate.toFixed(1);$("heroRate").textContent=cityRate.toFixed(1);let counts={};reportsAgglo.forEach(x=>counts[x.territory]=(counts[x.territory]||0)+1);let ranked=Object.entries(counts).map(([name,count])=>({name,count})).sort((a,b)=>b.count-a.count);$("ranking").innerHTML=ranked.map((x,i)=>'<div class="rank-row"><span>'+(i+1)+'</span><div>'+esc(x.name)+'<div class="bar"><i style="width:'+Math.min(100,x.count/(ranked[0]?.count||1)*100)+'%"></i></div></div><b>'+x.count+'</b></div>').join("")||'<div class="feed-empty">Aucun signalement sur la période.</div>';let cc={};categories.forEach(c=>cc[c]=0);reports.forEach(x=>cc[x.category]=(cc[x.category]||0)+1);const categoryRows=categories.map(c=>({category:c,count:cc[c],color:colors[c]||"#868e96",percent:reports.length?Math.round(cc[c]/reports.length*100):0})).filter(x=>x.count>0).sort((a,b)=>b.count-a.count);$("categoryStats").innerHTML=categoryRows.map(x=>'<div style="display:grid;grid-template-columns:10px minmax(0,1fr) auto;gap:10px;align-items:center;padding:10px 0;border-bottom:1px solid #eeeae3"><span style="width:9px;height:9px;border-radius:50%;background:'+x.color+';display:block"></span><div><div style="display:flex;justify-content:space-between;gap:8px;font-size:10px;font-weight:700"><span>'+esc(x.category)+'</span><span style="font-size:9px;color:#77736b;font-weight:500">'+x.count+' signalement'+(x.count>1?'s':'')+'</span></div><div class="bar" style="margin-top:6px;height:5px"><i style="width:'+Math.round(x.count/(categoryRows[0]?.count||1)*100)+'%;background:'+x.color+'"></i></div></div><strong style="font-size:10px;color:#77736b;min-width:34px;text-align:right">'+x.percent+'%</strong></div>').join("")||'<div class="feed-empty">Aucun signalement sur la période.</div>';$("feed").innerHTML=reports.slice(0,30).map(x=>'<div class="feed-item"><b>'+esc(x.category)+'</b>'+(x.subtype?" — "+esc(x.subtype):"")+'<div class="sub">'+esc(x.other_name||"")+'</div><div class="addr">'+esc(x.address)+'</div><div class="meta">'+esc(x.territory)+" · "+new Date(x.created_at).toLocaleString("fr-FR")+"</div></div>").join("")||'<div class="feed-empty">Aucun signalement sur la période.</div>'}
async function recenterSelection(){const agg=$("scope").value==="Agglo";const commune=agg?$("communeFilter").value:"Saumur";if(commune==="Toutes"){map.setView(saumur,11);return}if(commune==="Saumur"){map.setView(saumur,14);return}try{const r=await fetch("https://nominatim.openstreetmap.org/search?format=json&limit=1&countrycodes=fr&q="+encodeURIComponent(commune+", Maine-et-Loire, France"));const d=await r.json();if(d[0])map.setView([+d[0].lat,+d[0].lon],13)}catch(e){map.setView(saumur,11)}}
function openReport(){$("reportModal").classList.add("open");setTimeout(()=>pickMap.invalidateSize(),100)}$("heroReport").onclick=openReport;$("topReport").onclick=e=>{e.preventDefault();openReport()};$("closeReport").onclick=()=>$("reportModal").classList.remove("open");$("gps").onclick=()=>navigator.geolocation?.getCurrentPosition(pos=>{const {latitude,longitude}=pos.coords;pickMap.setView([latitude,longitude],16);setPick(latitude,longitude)});$("search").onclick=async()=>{const q=$("address").value.trim();if(!q)return;const r=await fetch("https://nominatim.openstreetmap.org/search?format=json&limit=1&countrycodes=fr&q="+encodeURIComponent(q+", Saumur Val de Loire"));const d=await r.json();if(d[0]){pickMap.setView([+d[0].lat,+d[0].lon],17);setPick(+d[0].lat,+d[0].lon)}};$("form").onsubmit=async e=>{e.preventDefault();const lat=+$("address").dataset.lat,lon=+$("address").dataset.lon;if(!lat||!lon)return alert("Placez le signalement sur la carte ou utilisez la position GPS.");const body={category:$("category").value,subtype:$("subtype").value,other_name:$("other").value,address:$("address").value,territory:$("territory").value,lat,lon,description:$("description").value};const r=await fetch("/api/reports",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)return alert(d.error||"Erreur");$("reportModal").classList.remove("open");e.target.reset();load();alert("Signalement publié.")};$("category").innerHTML='<option value="">Catégorie</option>'+categories.map(x=>`<option>${x}</option>`).join("");load();setTimeout(()=>{map.invalidateSize();pickMap.invalidateSize()},250);